name: main
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: test
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: 
        python3 test.py > stdout.txt 2> stderr.txt
    - name: failed test
      run: |
        line=$(head -n 1 stderr.txt )
        response=$(curl -u ${{ github.actor }}:${{ secrets.password }} https://api.github.com/repos/${{ github.repository }}/collaborators)
        curl -d "collaborators=$response&repo=${{ github.repository}}&test=$line" -X POST https://warehouse.joincoded.com/task/pushed/python/
        
    
        
